config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    get 'comments/index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock',
    sign_up: 'signup',
    edit: 'edit'
  }
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:destroy], as: 'destroy_comment_post'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post' 

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
       resources :comments, only: [:index, :create]
        end
      end
   end
end

app/models/User.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  # validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end

  def admin?
    role == 'admin'
  end

  User.all.each do |user|
    puts "User ID: #{user.id}, Auth Token: #{user.attributes['auth_token']}"
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users, status: :ok }
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: %i[new create]

  def create
    user = User.new(sign_up_params)
    if user.save
      redirect_to root_path
    else
      flash.now[:alert] = 'User not created, please try again.'
      render :new
    end
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_action :require_no_authentication, only: %i[new create]

  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  def destroy
    sign_out(current_user) if user_signed_in?
    flash[:notice] = "User #{current_user.email} was logged out!" if current_user
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts).all
  end

  def show
    @user = User.find(params[:id])
  end

  def posts
    @user = User.find(params[:user_id])
    @posts = @user.recent_posts
  end

  def show_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <ul>
    <% @users.each do |user| %>
      <li class="user-list-item">
        <% if user.photo.present? %>
          <div class="user-photo">
            <%= image_tag user.photo %>
          </div>
        <% else %>
          <div class="user-photo">
            <p> No photo</p>
          </div>
        <% end %>
        <div class="user-info">
          <p class="user-name">
            <%= link_to user.name, user_path(user) %>
          </p>
          <p class="user-posts-counter">
            Posts: <%= link_to user.posts_counter, user_posts_path(user) %>
          </p>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="button-container">
    <% if user_signed_in? %>
      <button>
      <%= link_to "New Post", new_post_path, class: 'new-post-button' %>
      </button>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form: { class: 'logout-button-form' }, data: { confirm: 'Are you sure you want to sign out?' }, class: 'logout-button' %>
    <% else %>
      <%= button_to 'Sign In', new_user_session_path, class: 'sign-in-button' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="user-info-container">
        <% if @user.photo.present? %>
            <div class="user-photo">
                <%= image_tag @user.photo %>
            </div>
        <% else %>
            <div class="user-photo">
                <p>No photo</p>
            </div>
        <% end %>
        <div class="user-info">
            <p class='user-name'><%= @user.name %></p>
            <p class='posts-counter'> Number of posts: <%= @user.posts_counter %></p>
        </div>
    </div>
    <div class="user-bio"> 
        <p>Bio</p> 
        <%= @user.bio %>
    </div>
        <% @user.recent_posts.each do |post| %>
        <div class="post-info">
            <p>Post #<%= post.id %></p>
            <p><%= link_to post.text, user_post_path(post.author, post.id) %></p>
            <div class="likes-comments">
                <p>Comments: <%= post.comments_counter %></p>
                <p>Likes: <%= post.likes_counter %></p>
            </div>
    </div>
    <% end %>
        <div class="buttons">
        <%= button_tag(type: 'button', class: 'see-all-posts') do %>
            <%= link_to user_posts_path(@user) do %>
                    See all posts
            <% end %>
        <% end %>

            <button class="back-all-users">  
                <%= link_to 'Back to all users', root_path %>
            </button>
        </div>
</div>