config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    get 'comments/index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock',
    sign_up: 'signup',
    edit: 'edit'
  }
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:destroy], as: 'destroy_comment_post'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post' 

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
       resources :comments, only: [:index, :create]
        end
      end
   end
end

app/models/Post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes

  after_save :update_user_posts_counter
  after_destroy :update_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_user_posts_counter
  after_destroy :update_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments(limit = 3)
    comments.includes(:author).order(created_at: :desc).limit(limit).to_a
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts

    render json: posts, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    # @user = User.includes(posts: [:author, comments: :author]).find(params[:user_id])
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, comments: :author)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
  end

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.build(post_params)
    puts "Current User ID: #{current_user.id}"
    puts "New Post Author ID: #{@post.author_id}"
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post created successfully'
    else
      puts @post.errors.full_messages # Debugging output to check validation errors
      redirect_to user_path(current_user), notice: 'Post not created'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.author), notice: 'Post deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="container">
  <div class='user-info-container'>
    <% if @user.photo.present? %>
      <div class="user-photo">
        <%= image_tag @user.photo %>
      </div>
    <% else %>
      <div class="user-photo">
        <p> No photo!</p>
      </div>
    <% end %> 
    <div class='user-info'>  
      <p class="user-name"><%= link_to @user.name, user_path(@user) %></p>
      <p class="posts-counter">Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <% @posts.includes(:comments, :author).each do |post| %>
    <div class="post-info">
      <p>Post #<%= post.id %></p>
      <p><%= link_to post.text.truncate(100), user_post_path(post.author, post.id) %></p>
      <div class="likes-comments">
        <p>Comments: <%= post.comments_counter %></p>
        <p>Likes: <%= post.likes_counter %></p>
      </div>
    </div>
      <div class="comments-section<%= ' with-border' if post.comments_counter > 0 %>">
      <% post.comments.includes(:author).limit(3).each do |comment| %>
        <div>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if @user.posts_counter >= 5 %>
    <div class="button-container">
      <button>
        <%= link_to 'Pagination', user_post_path(@user, @posts.first) %>
      </button>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= form_with scope: :post, url: posts_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="post-info">
    <div class="post-header">
      <p>Post #<%= @post.id%> by <%= link_to @post.author.name, user_path(@post.author) %></p>
      <div class="likes-comments">
        <p>Comments: <%= @post.comments_counter %></p>
        <p>Likes: <%= @post.likes_counter %></p>
      </div>
    </div>
    <p class="post-text"><%= @post.text %></p>
  </div>
    <div class="comment-section<%= ' with-border' if @post.comments_counter > 0 %>">
    <% @post.comments.each do |comment| %>
      <div>
        <p><%= link_to comment.author.name, user_path(@post.author, @post, comment)%>: <%= comment.text %></p>
      </div>
      <% if can?(:destroy, comment) %>
       <%= button_to 'Delete Comment', user_post_comment_path(@post.author, @post, comment, comment_id: comment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'delete-button' %>
      <% end %>
    <% end %>
  </div>
  <div class="button-container-view">
    <button>
      <%= link_to 'Back to Posts', user_posts_path(@user) %>
    </button>
    <button>
    <%= link_to 'Add Comment', new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), class: 'add-comment-button' %>
    </button>
    <%= button_to 'Like', user_post_likes_path(user_id: @post.author.id, post_id: @post.id), method: :post, class: 'like-button' %>
    <% if can?(:destroy, @post) %>
      <%= button_to 'Delete', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
    <% end %>
  </div>
</div>